services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: gateway-otel-collector
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "13133:13133"